spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb+srv://Test:Test@cluster11.huvsy.mongodb.net/test
      database: Shoppingcart
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    path: /order-service-swagger.html
  operationsSorter: method